version: '3.9'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=tinec
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  
  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

  backend:
    container_name: backend
    build: .
    image: tinec/backend
    ports:
      - "5000:5000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=tinec
      - PG_PASSWORD=123456
      - PG_HOST=node_db
    depends_on:
      - postgres


volumes:
  data: